services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - database
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run serve
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/frontend/node_modules
    expose:
      - 8080
    env_file:
      - ./.env.dev
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - 1337:80
      - 1338:81
    depends_on:
      - backend
      - frontend

  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.env.dev

volumes:
  postgres_data:
  node_modules: